In [1]:
import pandas as pd

In [2]:
print(pd.__version__)

3.0.1


In [3]:
import unsloth
print(unsloth.__version__)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
ERROR 03-20 04:16:08 [gpt_oss_triton_kernels_moe.py:34] Failed to import Triton kernels. Please make sure your triton version is compatible. Error: No module named 'triton_kernels.routing'
🦥 Unsloth Zoo will now patch everything to make training faster!
2026.3.8


In [4]:
# 기존 설치본 삭제 및 캐시 정리 후 재설치
!pip uninstall unsloth triton -y
!pip install --no-cache-dir "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-cache-dir --force-reinstall "triton==3.0.0"

Found existing installation: unsloth 2026.3.8
Uninstalling unsloth-2026.3.8:
  Successfully uninstalled unsloth-2026.3.8
Found existing installation: triton 3.5.1
Uninstalling triton-3.5.1:
  Successfully uninstalled triton-3.5.1
  Cloning https://github.com/unslothai/unsloth.git to /tmp/pip-install-tler28vf/unsloth_90cc92e70fbe4eb19dce5e9ae8221c96
  Running command git clone --filter=blob:none --quiet https://github.com/unslothai/unsloth.git /tmp/pip-install-tler28vf/unsloth_90cc92e70fbe4eb19dce5e9ae8221c96
  Resolved https://github.com/unslothai/unsloth.git to commit d0e5a1d61e5cbb6fb426849da7de3cc3dc56f2ce
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.4/170.4 MB 13.9 MB/s  0:00:12m0:00:0100:01
  Created wheel for unsloth: filename=unsloth-2026.3.8-py3-none-any.whl size=29260940 sha256=29418639d1592673587c7f0ca47ffa598ba6eee326f49445d020781dcf9e196e

In [4]:
import torch
print(torch.__version__)

2.9.1+cu128


In [5]:
import torch
major_version, minor_version = torch.cuda.get_device_capability()
print(major_version, minor_version)

8 6


In [6]:
from unsloth import FastLanguageModel

In [7]:
from IPython.display import Image

Image(url='https://mblogthumb-phinf.pstatic.net/MjAyMDA1MjVfMTM0/MDAxNTkwMzc4MTY4MDQy.iOzxIfhew8Bsto7uqNW3QYj-k9bysF775jXYLECD6bwg.uMJ87NPURvklkXF2TXFnygaSnc32erHm_mXbnKgvO24g.PNG.nabilera1/image.png?type=w800')

In [8]:
import torch
import numpy as np
print(torch.__version__)

2.9.1+cu128


In [9]:
arr = np.array([1, 3, 5, 7, 9])
print(arr)
print(arr.dtype)
print(type(arr))

[1 3 5 7 9]
int64
<class 'numpy.ndarray'>


In [10]:
t1 = torch.from_numpy(arr)
print(t1)
print(t1.dtype)
print(t1.type())
print(type(t1))

tensor([1, 3, 5, 7, 9])
torch.int64
torch.LongTensor
<class 'torch.Tensor'>


In [11]:
t2 = torch.as_tensor(arr)
print(t2)
print(t2.dtype)
print(t2.type())
print(type(t2))

tensor([1, 3, 5, 7, 9])
torch.int64
torch.LongTensor
<class 'torch.Tensor'>


In [12]:
arr[0] = 999

In [13]:
print(f't1: {t1}')
print(f't2: {t2}')

t1: tensor([999,   3,   5,   7,   9])
t2: tensor([999,   3,   5,   7,   9])


In [14]:
arr = np.array([1, 3, 5, 7, 9])
print(arr)
print(arr.dtype)
print(type(arr))

[1 3 5 7 9]
int64
<class 'numpy.ndarray'>


In [15]:
t3 = torch.tensor(arr)
print(t3)
print(t3.dtype)
print(t3.type())
print(type(t3))

tensor([1, 3, 5, 7, 9])
torch.int64
torch.LongTensor
<class 'torch.Tensor'>


In [16]:
arr[0] = 999

In [17]:
print(f't3: {t3}')

t3: tensor([1, 3, 5, 7, 9])
